export const RESET_STATE = "RESET_STATE";

export const SET_SNACKBAR = "SET_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const ADMIN_AUTH_SET_IS_LOGGED_IN = "ADMIN_AUTH_SET_IS_LOGGED_IN";

export const INTRO_SET = "INTRO_SET";
export const INTRO_SET_DIALOG_COLOR = "INTRO_SET_DIALOG_COLOR";
export const INTRO_SET_DIALOG_IMAGE = "INTRO_SET_DIALOG_IMAGE";
export const INTRO_SET_COLOR = "INTRO_SET_COLOR";
export const INTRO_SET_IMAGE = "INTRO_SET_IMAGE";
export const INTRO_SET_TEXT = "INTRO_SET_TEXT";

export const PROJECTS_SET = "PROJECTS_SET";

export const PROJECT_SET = "PROJECT_SET";
export const PROJECT_SET_DIALOG_COLOR = "PROJECT_SET_DIALOG_COLOR";
export const PROJECT_SET_DIALOG_MEDIA = "PROJECT_SET_DIALOG_MEDIA";
export const PROJECT_SET_DIALOG_EDIT_MEDIA = "PROJECT_SET_DIALOG_EDIT_MEDIA";
export const PROJECT_SET_TITLE = "PROJECT_SET_TITLE";
export const PROJECT_SET_DESCRIPTION = "PROJECT_SET_DESCRIPTION";
export const PROJECT_SET_COLOR = "PROJECT_SET_COLOR";
export const PROJECT_SET_MEDIA_LIST = "PROJECT_SET_MEDIA_LIST";
export const PROJECT_MEDIA_LIST_ADD = "PROJECT_MEDIA_LIST_ADD";
export const PROJECT_MEDIA_LIST_ADD_VIDEO = "PROJECT_MEDIA_LIST_ADD_VIDEO";
